apiVersion: v1
items:
- apiVersion: conventions.apps.tanzu.vmware.com/v1alpha1
  kind: PodIntent
  metadata:
    creationTimestamp: "2022-09-20T04:21:21Z"
    generation: 2
    labels:
      app.kubernetes.io/component: intent
      app.kubernetes.io/part-of: python-function-app
      apps.kubernetes.io/name: python-function-app
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: web
      carto.run/cluster-template-name: convention-template
      carto.run/resource-name: config-provider
      carto.run/supply-chain-name: source-to-url
      carto.run/template-kind: ClusterConfigTemplate
      carto.run/workload-name: python-function
      carto.run/workload-namespace: my-apps
      tanzu.app.live.view.application.actuator.port: "8080"
    name: python-function
    namespace: my-apps
    ownerReferences:
    - apiVersion: carto.run/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Workload
      name: python-function
      uid: e23a3ece-836e-4b61-ad73-ac5fcb0f6ebc
    resourceVersion: "947037"
    uid: 3582b5bf-4d6a-4a58-876e-ba89c63ffe55
  spec:
    serviceAccountName: default
    template:
      metadata:
        annotations:
          autoscaling.knative.dev/minScale: "1"
          developer.conventions/target-containers: workload
        labels:
          app.kubernetes.io/component: run
          app.kubernetes.io/part-of: python-function-app
          apps.kubernetes.io/name: python-function-app
          apps.tanzu.vmware.com/has-tests: "true"
          apps.tanzu.vmware.com/workload-type: web
          carto.run/workload-name: python-function
          tanzu.app.live.view.application.actuator.port: "8080"
      spec:
        containers:
        - image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-09-09-2022-06-55-11-853383988/python-function-my-apps@sha256:24cbd40b69d08097e0fb7ef196d4e2e73ce8f07866e66597f3c90486f60e2b41
          name: workload
          securityContext:
            runAsUser: 1000
        serviceAccountName: default
  status:
    conditions:
    - lastTransitionTime: "2022-09-20T04:21:24Z"
      message: ""
      reason: Applied
      status: "True"
      type: ConventionsApplied
    - lastTransitionTime: "2022-09-20T04:21:24Z"
      message: ""
      reason: ConventionsApplied
      status: "True"
      type: Ready
    observedGeneration: 2
    template:
      metadata:
        annotations:
          autoscaling.knative.dev/minScale: "1"
          conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
          developer.conventions/target-containers: workload
        labels:
          app.kubernetes.io/component: run
          app.kubernetes.io/part-of: python-function-app
          apps.kubernetes.io/name: python-function-app
          apps.tanzu.vmware.com/has-tests: "true"
          apps.tanzu.vmware.com/workload-type: web
          carto.run/workload-name: python-function
          tanzu.app.live.view.application.actuator.port: "8080"
      spec:
        containers:
        - image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-09-09-2022-06-55-11-853383988/python-function-my-apps@sha256:24cbd40b69d08097e0fb7ef196d4e2e73ce8f07866e66597f3c90486f60e2b41
          name: workload
          resources: {}
          securityContext:
            runAsUser: 1000
        serviceAccountName: default
kind: List
metadata:
  resourceVersion: ""
